[project]
name = "reflection-agent-blog-quality-assesment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "moinul95", email = "moinul0817@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
reflection-agent-blog-quality-assesment = "reflection_agent_blog_quality_assesment:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
